### ISSUE TITLE
Change obkv to support more than 256 fields

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/milli#107]
Right now [obkv](https://lib.rs/obkv) only supports no more than 256 fields.

We will be able to change that by using a trait on the key type when [this playground compile](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=85050ff56443dfce28f1d596d1565edb) and this is related to [this announcement](https://blog.rust-lang.org/2021/02/26/const-generics-mvp-beta.html) (will be available in 1.51).

**Comment by Kerollmops** [comment]
I have opened [a draft PR on the obkv crate](https://github.com/Kerollmops/obkv/pull/1) that is finished, it maybe needs a little polish phase.

**Comment by curquiza** [comment]
Finished!
