### ISSUE TITLE
Implement stop words

### ISSUE THREAD

**Issue by curquiza** [meilisearch/milli#111]
Implement stop words to make transplant iso with the current version of MeiliSearch

**Comment by LegendreM** [comment]
# Possible implementation
To implement `stopwords` in milli, there are several parts to change:

- [ ] Add `stopwords` indexation during indexation of  `settings`
- [ ] Pass `stopwords` in parameters during indexation of `documents`
- [ ] Change `Tokenizer` call during `search` (query tokenization part)

## Tokenizer
The [method](https://github.com/meilisearch/Tokenizer/blob/31ba3ff4a15501f12b7d37ac64ddce7c35a9757c/src/analyzer.rs#L115-L132) used to initialize `Tokenizer` in the different parts is called like this [test](https://github.com/meilisearch/Tokenizer/blob/31ba3ff4a15501f12b7d37ac64ddce7c35a9757c/src/analyzer.rs#L314-L321).

```rust
let stop_words = Set::default();
let analyzer = Analyzer::new(AnalyzerConfig::default_with_stopwords(&stop_words));
```

## Settings

TBD @Kerollmops 

## Indexation

In the indexation of documents, `stopwords` are passed to [this function](https://github.com/meilisearch/milli/blob/6b7cc0022b37d0ec85103a0f4b5dc4a8fed8af97/milli/src/update/index_documents/store.rs#L80-L90) and are used [later](https://github.com/meilisearch/milli/blob/6b7cc0022b37d0ec85103a0f4b5dc4a8fed8af97/milli/src/update/index_documents/store.rs#L144) by the `Tokenizer`.

## Search

Query tokenization is done [here](https://github.com/meilisearch/milli/blob/6b7cc0022b37d0ec85103a0f4b5dc4a8fed8af97/milli/src/search/mod.rs#L94-L98)
