### ISSUE TITLE
Introducing a set of benchmarks

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/milli#132]
After a discussion with @curquiza and @irevoire, we decided that it was time to introduce some benchmarks into the repository. They will help us detect regression and help us improve the search engine.

The first step is to introduce benchmarks for the search phase, where we need a fixed dataset with a decent amount of documents but also interesting properties i.e. attributes that can be easily faceted.

## The list of datasets

 - Songs with more than 115 million records (title, album, artist, genre, country, released-timestamp, duration-float) that we will extract a sample of 1 million records from.
 - Wikipedia articles with more than 5 million records (body, title, URL) that we will extract a sample of 500k records from.

## The list of benchmarks

Making a thorough list of benchmarks will help us identified where the problems are located, but doing too much benchmark will make the benchmark list hard to maintain. This is why we chose to create only 7 benchmarks for each dataset.

### With the default criteria list

All those benchmarks will use an index set with all the default criteria In the default order.

- placeholder with `filters` (not for the Wikipedia dataset because not relevant).
- prefix search (e.g. `a` alone).
- basic queries without quotes (e.g. `monica belucci`).
- basic queries with quotes (e.g. `"monica" "belucci"`) to disable ngrams, word concatenation, and prefix words.

### With a basic search query

All those benchmarks will be triggered with basic search queries that will reduce the size of the query tree. For example, the query `monica belucci` will trigger the word splitting, ngrams concatenation, or prefix words on the query tree builder. This represents the most common queries that users will execute on the front end.

- on each criterion one by one
- with `asc/desc` alone
- with `asc/desc` at the top of the default criteria (trigger the `sortBy` behavior)

**Comment by curquiza** [comment]
Closed by #207
