### ISSUE TITLE
Facets values are not normalized

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/milli#133]
While implementing `distinct`, I realized that facets are not being normalized, but only lowercased. This is an issue since the representation on the facet that is being parsed from the facet expression could differ from the one made by the tokenizer, and stored in the database.

This affects both facet filters, and disctinct (#125).

The Fix woud require to use to the tokenizer to normalize the string facet values when the facet is parsed here: https://github.com/meilisearch/milli/blob/main/milli/src/search/facet/facet_condition.rs#L61-L64, and in the relevant part in the distinct part.

**Comment by curquiza** [comment]
We don't know yet if we are going to implement it. Removing it from the v0.21.0 milestones.

**Comment by curquiza** [comment]
Checked with @Kerollmops and @gmourier, we decided to trim and only lowercased the facet values.
