### ISSUE TITLE
Support synonyms in the engine

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/milli#144]
Milli must support the synonyms. Synonyms can be more than one word and are already supported in the query tree construction logic, we only need to introduce methods to set and save them on disk.

You can find more information on [the official MeiliSearch documentation](https://docs.meilisearch.com/reference/api/synonyms.html#synonyms).

1. Introduce a field in [the Settings struct to accept a list of synonyms](https://github.com/meilisearch/milli/blob/2bcdd8844c4ec9f6f8a34617ea0e4321fa633c0c/milli/src/update/settings.rs#L29-L35).
1. Store this list of synonyms in an efficient way in the key-value store.
1. Fetch this list in [the Context trait implementation of the `QueryTreeBuilder`](https://github.com/meilisearch/milli/blob/2bcdd8844c4ec9f6f8a34617ea0e4321fa633c0c/milli/src/search/query_tree.rs#L188-L190).

## Details about the synonyms

As explained above the synonyms can only be declared one-way (i.e. android gives smartphone), if a user needs to declare a two-way synonym (i.e. wolverine gives logan and logan gives wolverine) it must be declared in both way by the user in the settings, that's expected behavior.

Here is the kind of JSON object that the engine will receive describing the list of synonyms:

```json
{
  "wolverine": ["logan"],
  "logan": ["wolverine"],
  "android": ["smartphone"],
  "wow": ["world of warcraft"],
  "world of worcraft": ["wow"]
}
```

### How can we store the synonyms?

We must find an efficient way to store the synonyms in LMDB (using heed), preferably in the main (polymorph) database like for stop-words. A HashMap serialized using serde JSON could do the job.

However, if a user has a lot of synonyms (think plurals or CJK), it could take a lot of time to deserialize the whole HashMap to, then, only fetch one list of associated synonyms. Finding a better way to store the synonyms (using another database) will be part of another issue, in the future.

### Normalize the synonyms!

When performing a search, the user query is compared to the list of synonyms, for synonyms to be matched correctly with the query words, both synonyms and query words must be normalized. Query words are already normalized (@LegendreM could you confirm?), we must not forget this step with synonyms when storing them. Both sides must be normalized (i.e. wolverine and logan).

If a synonym is found to be multiple words, it must be split using the tokenizer and stored splitter, on both sides.

**Comment by shekhirin** [comment]
> the official MeiliSearch documentation.

I suppose link to the doc isn't correct 😄 
![image](https://user-images.githubusercontent.com/5773434/113750101-09d41980-9713-11eb-89f0-247319dd6a1d.png)

**Comment by shekhirin** [comment]
I think I can start working on this one and present a PR draft in a while 🙂

**Comment by shekhirin** [comment]
@Kerollmops how's about filling another issue regarding synonyms storage optimization (as you said, it may be another DB)?

**Comment by Kerollmops** [comment]
@shekhirin thank you, I just updated the relevant part of the issue, I hope we already have a mutable transaction in the query builder to be able to fetch the synonyms from the database.
