### ISSUE TITLE
Limit the number of words in a query

### ISSUE THREAD

**Issue by curquiza** [meilisearch/milli#147]
For safety reasons, we need to fix a limit on the number of words in a query.

We need to define:
- The number of this limit. We should add [a new parameter in the Search builder struct](https://github.com/meilisearch/milli/blob/2bcdd8844c4ec9f6f8a34617ea0e4321fa633c0c/milli/src/search/mod.rs#L31-L40) to define the maximum number of words that will be considered by the query builder.
- How the engine behaves if there are more words than the limit? A basic behavior could be to just ignore the words that are after the limit.

**Comment by curquiza** [comment]
Related to https://github.com/meilisearch/transplant/issues/119

**Comment by shekhirin** [comment]
I tried to make a quick prototype and realized it would be convenient to use `take` for Tokenizer's `TokenStream` to limit number of words in the query so it'll be something like
```rust
let result = analyzer.analyze(query);
let tokens = result.tokens().take(self.words_limit).collect();
builder.build(tokens)?
```

So @Kerollmops I think we need a change like this on the Tokenizer's side too to be able to `collect`.
```rust
impl<'a> FromIterator<Token<'a>> for TokenStream<'a> {
    fn from_iter<T: IntoIterator<Item=Token<'a>>>(iter: T) -> Self {
        Self {
            inner: Box::new(iter.into_iter().collect::<Vec<_>>().into_iter()),
        }
    }
}
```

WDYT?

**Comment by Kerollmops** [comment]
@shekhirin I think this is a great and simple idea to implement the limit in the number of query words.

However, it must be polished a little bit as the `Analizer::tokens` iterator also returns the separators. We should ignore them in the take count as the query builder must be aware of them to accurately construct the query tree. Also, note that when the number of words is effectively limited we must ensure that the last token is a separator to make sure that we don't create a query tree with a prefix as the last word.

**Comment by LegendreM** [comment]
Hello @shekhirin!
Let me suggest a simpler approach,
[here](https://github.com/meilisearch/milli/blob/6e126c96a92c3d07257fe364d2d1780a3ee2ae16/milli/src/search/query_tree.rs#L479) we have a function that post-parse the tokenizer results taking into account potential prefixes and phrases (word surrounded by double quotes `"`).
The result of this function is directly used to build the query tree.
The [result](https://github.com/meilisearch/milli/blob/6e126c96a92c3d07257fe364d2d1780a3ee2ae16/milli/src/search/query_tree.rs#L225) could be shrunk before passing it to `create_query_tree`.

**Comment by shekhirin** [comment]
@LegendreM sounds good. We also won't need to change Tokenizer in that case. I'll look into it and fix the PR, thanks! 🙂
