### ISSUE TITLE
Fix stop words

### ISSUE THREAD

**Issue by curquiza** [meilisearch/milli#150]
_Following https://github.com/meilisearch/transplant/pull/135#pullrequestreview-630336982_

I have an issue when using stop-words:
- add documents with `title: "the hobbit"`
- add `the` as stop-words
- search for "the hobbit"

-> I don't get any result, I should get my document with "the hobbit" if I'm not wrong.

**Comment by curquiza** [comment]
We should add tests to check the stop words impact the search results as expected

**Comment by irevoire** [comment]
I can reproduce the bug
