### ISSUE TITLE
[feature request] Per-search sorting

### ISSUE THREAD

**Issue by A5rocks** [meilisearch/milli#155]
I know this is already at https://github.com/meilisearch/MeiliSearch/issues/730 ...

However, I believe it's probably easiest to add this feature while the search is still under development. (feel free to close this if you believe differently though, haha)

**Comment by curquiza** [comment]
Hello @A5rocks, we indeed plan to add the `sortBy`. It will not be available for the v0.21.0, but will be in one of the next releases.
FYI, this new search engine (milli) can easily integrate the `sortBy`, so be sure it will come 🙂 But this is not our priority for the moment. Our priority is to release this new search engine by staying as ISO as possible with the current MeiliSearch.

I will close this issue in favor of the roadmap (https://roadmap.meilisearch.com/c/32-sort-by) and the MeilISearch's issue (https://github.com/meilisearch/MeiliSearch/issues/730)

Thanks for your feedback anyway, and we are aware the `sortBy` is a feature requested by a lot of users, so don't worry, we will integrate it 🙂

**Comment by A5rocks** [comment]
Thanks! Just wanted to make sure the rewrite wouldn't write out the current system, where you can pass criteria to the search function itself.

**Comment by curquiza** [comment]
@Kerollmops anticipated the `sortBy` when implementing the new search engine (milli) if I'm correct! 😉

**Comment by shafikhaan** [comment]
@A5rocks any ETA on `sortBy` ?

**Comment by A5rocks** [comment]
On my fork? It's completed lol (reversing doesn't work very well though).

I don't plan to actually maintain the fork though, it's just there as a quick hack to prove feasibility and to not use elasticsearch.
