### ISSUE TITLE
Implemention for Exactness criterion

### ISSUE THREAD

**Issue by LegendreM** [meilisearch/milli#165]
# Prior Art 
Algolia explains the Exact criterion like:
> Records with words that match query terms exactly are ranked higher. The more matching words in a record’s attribute, the higher a record is ranked. By default, an exact match occurs when a full word in a query is matched without typos to a word in an attribute. An inexact match is one that has typos or only matches on a prefix.

> Additionally, synonym matching and plural/singular matching are considered exact. Thus, a word is considered an exact match if its synonym matches a query exactly.

Adding some exceptions:
> [...] single-word matches on multi-word attributes aren’t considered exact matches by default [...]
> [...] Multiword synonyms are not counted as exact matches by default [...]

## Brief
for each word of the query we match documents:
- without typo
- without prefix
- without ngrams
- without complex synonyms
- without word split

if the query only contains 1 word, only 1-word attributes can match.

## Pro & Con

This behavior of the Exact criterion gives a better rank to documents that match the words of the original query, ranking `ngrams`, `complex synonyms`, and `word split` after.
But the exception `if the query only contains 1 word, only 1-word attributes can match` will only boost documents that have an attribute that exactly contains the query word and that's all. No boost on non `complex synonyms`, and non `word split`.
Useful when an ID is searched but in others cases, it could impact the relevancy.
Moreover, when we a multi-words query, attributes that exactly contains the query are not boosted.

At last, because meilisearch is a `search as you type` engine, attributes that exactly begin by the original query could be boosted.

# Possible Behavior in milli

we could divide Exact into several layers of ranking:

## 1: Try to match exactly the query in an attribute
Any document that has an attribute that contains exactly the query:
- without typo
- without prefix
- without ngrams
- without complex synonyms
- without word split
- with words in the right order

has a rank of `0` (perfect match)

## 2: Try to match exactly the query at the start of an attribute
Any document that has an attribute that contains the query at the `n` firsts positions:
- without typo
- without prefix
- without ngrams
- without complex synonyms
- without word split
- with words in the right order

**OR**

Any document that has an attribute that contains exactly the query:
- without typo
- without ngrams
- without complex synonyms
- without word split
- with words in the right order
- **with the last word considered as prefix**

has a rank of `1` (the user didn't finish to tip the search but the final query could be an exact match)

## 3: Try to match exactly the word of the query anywhere in the document
Any other document has a rank of `2` + `1` for each word that is not an exact match.

a word is considered as an exact match when it matches:
- without typo
- without prefix
- without ngrams
- without complex synonyms
- without word split

_**note** @LegendreM: forbidding typos in the `Exact` criterion overlap the work of the `Typo` criterion, we should think about avoiding this conflict by allowing typos in the `Exact` criterion. It seems strange, but, thinking about the interaction between criteria, it could be logical._

**Comment by gmourier** [comment]
Huge thanks for this proposal. 🙏

**Comment by gmourier** [comment]
If I'm understanding it the right way the proposal is kind of the TypeSense behavior.

Typesense calculates a `_text_match score` for ranking the documents about text relevance.

`_text_match score` is computed from different criteria like frequency, edit distance, proximity and, ordering of query_by fields.

If documents have the exact same `_text_match` score, TypeSense accepts two more numerical fields in the sort_by parameter to break the tie.

E.g. `sort_by=_text_match:desc,price:desc,rating:desc`

It is possible to put a numerical field before the` _text_match score`.

E.g. sort_by=`price:desc,_text_match:desc`

`sort_by parameter` is set at query time.

**Comment by gmourier** [comment]
I will open a specification for comment to move the discussion.

**Comment by gmourier** [comment]
The specification has been opened to move our discussions [there](https://github.com/meilisearch/specifications/pull/36).
