### ISSUE TITLE
User-Restricted Access to Data

### ISSUE THREAD

**Issue by bionicles** [meilisearch/milli#167]
https://www.algolia.com/doc/guides/security/api-keys/how-to/user-restricted-access-to-data

how hard would it be to do this on meilisearch? so folks can search shared datasets and see only authorized data

not sure where to put this issue, but milli seems cool

**Comment by curquiza** [comment]
Hello @bionicles!
thanks for using MeiliSearch :)
This feature is already under consideration in our roadmap: https://roadmap.meilisearch.com/c/82-authorization-keys. Don't hesitate to upvote it and let us feedback about what you expect for this feature!
Even if milli is the search library, this repository is not where we expect new feature request, you can use our roadmap for this: https://roadmap.meilisearch.com/tabs/1-under-consideration
It would be nice to have your opinion about other features/changes you might need, feel free to use it 😁

I close this issue but be sure we have the user-restricted access in mind for the future 🙂
