### ISSUE TITLE
Not generate the documents ids by default.

### ISSUE THREAD

**Issue by curquiza** [meilisearch/milli#171]
Related to https://github.com/meilisearch/transplant/issues/165#issuecomment-827717649

> This should be highly related to this [line in the milli indexer](https://github.com/meilisearch/milli/blob/3bcc1c0560857163968500169ac73385be3b9d5d/milli/src/update/index_documents/mod.rs#L311-L313), we should maybe change [the default setting to not generate the documents ids by default](https://github.com/meilisearch/milli/blob/3bcc1c0560857163968500169ac73385be3b9d5d/milli/src/update/index_documents/mod.rs#L294).

**Comment by Kerollmops** [comment]
Hey @shekhirin, If you got time, that's one easy issue here 😃
