### ISSUE TITLE
Stats return inconsistent information

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/milli#174]
Version: 0.21.0-alpha.4
Dataset: movies.json

The stats of the index `movies` returns the following information: 
`{"numberOfDocuments":19546,"isIndexing":false,"fieldsDistribution":{"genres":19457,"id":19547,"overview":19547,"poster":19547,"release_date":19547,"title":19547}}`

As you can see `numberOfDocuments`: 1954**6**
But the fields distribution show 1954**7**

In version 0.20.0, the returned information is coherent:

`{"numberOfDocuments":19546,"isIndexing":false,"fieldsDistribution":{"genres":19456,"id":19546,"overview":19546,"poster":19546,"release_date":19546,"title":19546}}`

**Comment by Kerollmops** [comment]
Hey @shekhirin, if you got time again, can you take a look at this one, please? If not no worries 😃

**Comment by shekhirin** [comment]
@Kerollmops yeah, I think so. I've worked on this one previously, so I suppose it would be easy one to figure out.
