### ISSUE TITLE
bug with filter syntax

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/milli#192]
In the filter syntax, this is valid:
```
filter:='["genres: comedy"]'
```

but this is not:
```
filter:='["genres : comedy"]'
```

The space in genre is taken into account in the attribute name. It needs to be trimmed, especially when it will be replaced with `=`

**Comment by Kerollmops** [comment]
It will be fixed by #184 when merged, I am in vacation and will not be able to merge it until I'm back.
