### ISSUE TITLE
Add test during indexation

### ISSUE THREAD

**Issue by curquiza** [meilisearch/milli#197]
We should add tests for the indexation.

**Comment by curquiza** [comment]
- [ ] add documents: the primary key (not id, but should contain id in the attribute name) can be inferred.
- [ ] same for update documents
- [ ] add documents: the primary key can be passed as parameter (don't use an attribute with id in the attribute name)
- [ ] same for update documents
- [ ] cannot add documents without primary key
- [ ] cannot update documents without primary key

**Comment by curquiza** [comment]
Should be done after #109

**Comment by ManyTheFish** [comment]
in milli the primary key **can't** be passed as parameter of `IndexDocument`
both test should be made in meilisearch:
- add documents: the primary key can be passed as parameter (don't use an attribute with id in the attribute name)
- same for update documents

**Comment by qdequele** [comment]
Make sense! The test has already been added to MeiliSearch as mentioned in https://github.com/meilisearch/MeiliSearch/issues/1440
