### ISSUE TITLE
Cargo clippy and cargo fmt in CI

### ISSUE THREAD

**Issue by curquiza** [meilisearch/milli#231]
- [x] use [this config](https://github.com/RoaringBitmap/roaring-rs/blob/master/rustfmt.toml)
- [ ] add `cargo clippy` and `cargo fmt` to [the CI](https://github.com/meilisearch/milli/blob/main/.github/workflows/test.yml)
- [ ] Fix clippy error in tests

**Comment by irevoire** [comment]
Clippy reported too many false positives, so we decided to wait until it improves a little before putting it in the CI.

**Comment by MoskalykA** [comment]
Hi, just do these two commands and make a pull request? If so I would like to take care of that

**Comment by unvalley** [comment]
I'll work on this!

**Comment by curquiza** [comment]
Hello @unvalley 

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

FYI, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊
