### ISSUE TITLE
Milli Light - a light version of meilisearch that runs on wasm.

### ISSUE THREAD

**Issue by b0xtch** [meilisearch/milli#241]
I have been attempting to strip down the original meilisearch core to make it run on WASM. The purpose of this is to enable it run on Dfinity. Is it possible to do it with this new repo?

**Comment by Kerollmops** [comment]
Hey @b0xtch,

This is indeed something that we want to propose at some point, being able to run this library without any dependency on the file system. This library is currently tied to heed (an LMDB wrapper) and therefore it is not possible right now. However, we want to maybe create a trait that exposes some sort of methods to get and iterate over the entries of any key-value store. We started experimenting with [the `Context` trait](https://github.com/meilisearch/milli/blob/b073fd49ea04fbb8da940f6357c952b34af94c0e/milli/src/search/criteria/mod.rs#L66-L119), it helps unit-test some of the criteria.
