### ISSUE TITLE
Unexpected log output

### ISSUE THREAD

**Issue by curquiza** [meilisearch/milli#263]
By trying to check if [this issue](https://github.com/meilisearch/MeiliSearch/issues/1240) was fixed, I tried to push the following dataset: https://gist.githubusercontent.com/okyanusoz/740961e3fc83dc75b9e0a199014e3efd/raw/d90d473b8f542ca29c78c5c6f076ee3a0bf93228/data.json

But I get unexpected logs (too many to paste them, I let you check by reproducing them manually).
I don't get these logs in v0.20.0

**Comment by curquiza** [comment]
Contributions are welcome! Feel free to ask any help or question.

**Comment by shekhirin** [comment]
Hi!

Is that a kind of logs you're talking about?
```bash
...
word "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" is too large to be saved
writing a chunk...
word "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" is too large to be saved
word [97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97] is too large to be saved
writing a chunk took 242.73µs
...
```

I got it with such invocation
```bash
➜  ~ value=$(printf -- 'a%.0s' {1..512}); echo '[{"id": 0, "value": "'$value'"}]' | curl -X POST -H 'Content-Type: application/json' --data-binary @- http://127.0.0.1:9700/documents
```

---

Seems like it's because here we're storing a pair of `(document_id, word)` as a key in LMDB
https://github.com/meilisearch/milli/blob/77de82aaa4ceaee9a5c4ec69c722bc709465f932/milli/src/update/index_documents/store.rs#L454-L485
but the limit on maximum key size not allowing us to store such big words
https://github.com/meilisearch/milli/blob/77de82aaa4ceaee9a5c4ec69c722bc709465f932/milli/src/update/index_documents/store.rs#L37

It can be proven with trying to set a value of length 507, so the key would be 511 bytes in length (4 bytes for key + 507 bytes for word). It works fine.
```bash
➜  ~ value=$(printf -- 'a%.0s' {1..507}); echo '[{"id": 0, "value": "'$value'"}]' | curl -X POST -H 'Content-Type: application/json' --data-binary @- http://127.0.0.1:9700/documents
```

---

It looks like a limitation of current implementation on maximum word length which possibly weren't in the previous version (before rewriting the engine), so I'm not sure there's an obvious fix for that. However, if so, I'd be happy to help with that.

**Comment by Kerollmops** [comment]
Hey @shekhirin,

It seems that those logs that you get are indeed what's we were referring to. Unfortunately, as you said, we can't do very much about them, but maybe always use [the `bstr` crate to log](https://docs.rs/bstr) the word that is too large. This way we avoid displaying an ugly array i.e. `[97, 97, 97, ...]`.

The `bstr` crate can wrap slices of bytes in [a `BStr` struct](https://docs.rs/bstr/0.2.16/bstr/struct.BStr.html) that is a better debuggable format by always trying to display valid characters when it can and backup on escaped character.

**Comment by shekhirin** [comment]
@Kerollmops sounds good. I made a PR with such fix https://github.com/meilisearch/milli/pull/334, could you check that I got your idea right?
