### ISSUE TITLE
Can't create two indexes?

### ISSUE THREAD

**Issue by irevoire** [meilisearch/milli#286]
Hello!
I was working on #274 and I got an issue I was not expecting.
Now I'm wondering if I'm badly using milli or if milli stores some information that it shouldn't store.

I created a small git repo to reproduce the bug: https://github.com/irevoire/milli_bug
All you have to do basically is run `cargo run` and you should get a panic:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UserError(PrimaryKeyCannotBeChanged)', src/main.rs:28:32
```

From what I see, even after deleting entirely the milli database and dropping the index. When we create a new index milli still contains document: https://github.com/meilisearch/milli/blob/main/milli/src/update/settings.rs#L435

**Comment by Kerollmops** [comment]
I am not quite sure I understand the problem, in your repository you didn't delete the index, you didn't even close it.

To be sure that it is effectively closed you must call `index.prepare_for_closing().wait()` on it, then you must delete the file from the filesystem like you currently do. Keep in mind that a memory-mapped file is always accessible until it is unmapped, that the reason why only deleting the file from the disk without quitting the program keeps the database alive.

**Comment by irevoire** [comment]
YES, thank you, that was totally the issue!
I was pretty sure to be the one who is wrong :smile:
