### ISSUE TITLE
Highlight corner case

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/milli#29]
The current version of the engine only return the words found in the different documents and it is up to the caller to highlight the document's words depending on the types found.

The problem is that the engine, when indexing, transforms the numbers into strings to be able to understand their meanings, returning a string to the caller that corresponds to the original number, therefore the caller must or must not, that is the question, transform the numbers into strings to be able to surround them with the `mark` tag.

The other complementary solution would be to not hihglight them, and not apply any transformation to the original document but in the mean time returning the strings to highlight to the client.

**Comment by curquiza** [comment]
Closed in favor of https://github.com/meilisearch/product/discussions/174
