### ISSUE TITLE
Possible issue when sorting documents lexicographically

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/milli#333]
We probably found a bug in the `sort`, `asc`, `desc` criterion when we sort on strings, the lexicographic sort feature seems broken and returns documents in an invalid order.

Note that algorithm used to lexicographically sort the documents is, indeed, lexicographic and the sort is based on the UTF-8 bytes of the strings, therefore it could give strange results when the first byte of a wide-character i.e. `嵐` is lower than the byte of an ascii one i.e. `U` and is displayed before the ascii one.

You can reproduce the possible bug with the movies.json dataset, by simply sending those settings:

```json
{
    "sortable_attributes": ["title"]
}
```

**Comment by Kerollmops** [comment]
Hey @shekhirin, maybe you can look at this issue, it does seem it has been made for you 😄

**Comment by shekhirin** [comment]
@Kerollmops that's awesome, I'll look into it.
