### ISSUE TITLE
Support prefix search of any length

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/milli#42]
Currently, when a user sends a search query to the engine, the words in the query are extracted and derivates are retrieved. Derivate words are words with typos and can also be prefixes (i.e. _he_ can match _hello_ or _hermit_).

When we want to find the derivates of the query words, we generate [DFAs](https://en.wikipedia.org/wiki/Deterministic_finite_automaton) that are used with the word FST (the word dictionary contains all the known words). This automaton will give us an iterator over all the words that match, but there can be many words.

When we got these words, we retrieve all the documents ids that contain those words. For each list of derivates of a query word we do a union of all the ids, then between each union we do an intersection, this corresponds to the list of candidates words to this query, therefore the more query words we got the fewer candidates we get.

### Performance issue

A very short token that is declared as a prefix (e.g. _se_) in a user query will force the engine to aggregate (doing a union) too many documents ids spread over too many words, slowing down the computation of the candidates.

### Fixing the issue

The idea would be to maintain two words dictionary, the current classic one which contains all the words in the database, and a new one, the prefixes dictionary which contains all of the important prefixes. The prefix dictionary is an FST that contains the prefixes which correspond to a lot of words.

Take for example the "a" prefix, it will be present in this prefix FST as something like 5% of the words dictionary matches this prefix. A basic algorithm would be to iterate through the word dictionary, in order, and group the words by their prefix letters, each time a group is found to be bigger or equal to a given threshold the prefix is added to the prefix dictionary. Once the prefix dictionary is ready, we are able to construct a `prefix-word-docids` database equivalent to the `word-docids`, where a prefix key gives all of the ids of the documents that we would have been able to find using the original words dictionary, it is equivalent to a cache.

We will have to find an accurate way to highlight the words in the output documents too, maybe using the DFAs.

**Comment by curquiza** [comment]
Done! 😄
