### ISSUE TITLE
Cloudflare Worker compatibility

### ISSUE THREAD

**Issue by Eduard-Hasa** [meilisearch/milli#443]
I'm new to meili and really loving the project. Was wondering is there any possibility I could use the milli project to index some key value data from a single cloudflare durable object. Would be an amazing approach to enable advanced queries to get ids of existing cloudflare durable objects.

Cloudflare workers are actually totally capable of running rust.

**Comment by Kerollmops** [comment]
Hey @Eduard-Hasa,

Welcome to the Meilisearch world! If the question is regarding the fact that you can compile the milli library into a wasm cloudflare-worker, I would answer no. The milli crate uses LMDB to store information on disk, this is something that we must change in the future for the library to be able to compile to a system without access to the disk.

> Cloudflare workers are actually totally capable of running rust.

We are aware of that and try to make sure that our future product will be able to run on such systems, this is quite complex when you need to couple this with performance in mind and fast access to mass data.

I have done some conclusive experiments on the Cloudflare worker system already, this is just that we need to polish that and make it good enough for production usage 😃

**Comment by bradjonesca** [comment]
Actually it may be that Fastly is more conducive to Meilisearch with the latest updates to their platform but I haven't experimented yet but will be after the 0.26 release.

**Comment by Eduard-Hasa** [comment]
This all sounds awesome. Please make any progress on running meili on serverless because I am sure there are plenty people excited over the roof about it like me :)

**Comment by Kerollmops** [comment]
Hey everyone, there indeed is more work to do to bring Meilisearch to the Cloudflare worker platform. As there is no disk space and the memory usage is highly limited, we don't think that we will port Meilisearch **as is** to the Cloudflare workers platform.

However, we thought about modifying or implementing another lightweight search engine that would support most of the best relevancy-oriented features of Meilisearch e.g., typo-tolerance, ranking-rules, and language support. This version would be disk-less and kind of immutable. We already have [a small demo of such an engine](https://wasau.kero.workers.dev/), but it is not production-ready.

I am closing this issue for now and will open a new one once we have plans to bring such a solution to the Cloudflare workers platform.
