### ISSUE TITLE
About documents deletion performances

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/milli#482]
This issue lists and describes the code used by the engine to delete documents, it is kind of a deep dive of [the _update/delete_documents.rs_ file](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs).

This issue is here as @MarinPostma noticed performance issues when he was inserting known documents (documents with an ID already present in the database). Marin was working [on improving the speed of the engine when for documents insertion](https://github.com/meilisearch/milli/pull/467).

When we insert documents that are not already known by the database, the engine uses the inserting side of the indexing system, but when it comes to already known documents we first delete the known ones to insert them a second time. This is where we see a big performance gap, the deletion part hasn't been optimized much.

**Comment by Kerollmops** [comment]
A first optimization that Marin thought about was that when we want to delete a single document from the database, for example, we were iterating over the whole inverted index (_word_docids_), he proposed that we tokenized the currently known document, extract the searchable words and iterate over these words instead of the whole index.

Unfortunately, we already do this kind of optimization. We store one-one relations between the words and positions that documents contain (and which are searchable), this LMDB database is named _docid_word_positions_. In the deletion algorithm, we first [collect all the words from the whole set of documents](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs#L157-L166) we want to remove from the database, then [we iterate only over this relatively small set of words and clean the associated data structures](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs#L204-L226) from the big inverted index (_word_docids_).

**Comment by Kerollmops** [comment]
When the engine indexes documents in the database, it also stores an association between the external and the internal id. This is stored in an FST. We should measure the time it takes [for the engine to do the job of removing the entries](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs#L187-L198) corresponding to the documents to remove from this FST.

**Comment by Kerollmops** [comment]
[The same kind of operation happens but for the words FST](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs#L228-L255), a data structure that contains the whole set of words known by the engine. This FST set is used by the engine to find words with typos for example. This part of the code can easily be skipped by using a simple condition: if the set of words to delete is empty just don't do any operation on the FST.

However, an empty set of words to delete cannot work when the documents' ids are unique and set as searchable. A situation like that means that when we delete a document from the database, its unique ID is part of the word FST and, as it is unique, only this document was referring to this word. The FST must be updated anyway.

**Comment by Kerollmops** [comment]
A lot of operations are _O(N)_ where _N_ is the size of the database:
 - [Removing documents ids from the _word_prefix_docids_ database](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs#L257-L276).
 - [Removing documents ids from the _word_prefix_pair_proximity_docids_ database](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs#L298-L316).
 - [Removing documents ids from the _word_pair_proximity_docids_ database](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs#L318-L337).
 - [Removing documents ids from the _word_position_docids_ database](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs#L339-L355).
 - [Removing documents ids from the _word_prefix_position_docids_ database](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs#L357-L374).
 - [Removing documents ids from the _field_id_word_count_docids_ database](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs#L376-L391). It is a small database thought, it should be fast to iterate on it.
 - [Removing documents ids from the _geo_ database](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs#L393-L409).
 - [Removing documents ids from the _facet_id_f64_docids_ database](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs#L548-L572).
 - [Removing documents ids from the _facet_id_string_docids_ database](https://github.com/meilisearch/milli/blob/d8dd357326956e30ee9c800fe1d827b7e85b7c5c/milli/src/update/delete_documents.rs#L488-L546).

This is too much and I am not sure about how we can optimize that easily, maybe Marin was right and we should probably store a set of documents to delete later.

**Comment by irevoire** [comment]
@Kerollmops should we close this issue?
Is there anything else to do from here?

**Comment by Kerollmops** [comment]
Indeed, we can close this issue. We will open a new one if we need to improve the current system.
