### ISSUE TITLE
Unchanged documents could be skipped during indexation

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/milli#569]
When we are indexing documents we could probably do a simple optimization and skip the documents that are exactly the same as before, it could potentially reduce the amount of work we do to remove and reinsert the given documents.

However, we are missing two metrics here:
 - How common is this use case? How many users will benefit from this change?
 - Would it really speed up the indexing process by a lot? Comparing the updated documents for every single update can take a lot of time and all the updates will suffer from this, even those that are really modifying the documents.

**Comment by irevoire** [comment]
It has already been implemented
