### ISSUE TITLE
`validate_document_id` function trims the id, but maybe shouldn't

### ISSUE THREAD

**Issue by loiclec** [meilisearch/milli#593]
See: https://github.com/meilisearch/milli/pull/561#discussion_r925394083

So a document such as:
```json
{
    "id" : "  hello  "
}
```
will have the id:
```json
"hello"
```
but according to [the Meilisearch documentation](https://docs.meilisearch.com/learn/core_concepts/primary_key.html#primary-field), spaces are not allowed in document ids. So one could argue that the document should not be accepted in the first place.

**Comment by irevoire** [comment]
And thus the documents
```
{ "id": " hello", ... }
{ "id": "hello ", ... }
```

Will be merged together, which is clearly a bug

**Comment by curquiza** [comment]
I've created https://github.com/meilisearch/meilisearch/issues/2640 to track it for the sprint.
Feel free to close this issue in favor of this one if you prefer

**Comment by curquiza** [comment]
Closed in favor of https://github.com/meilisearch/meilisearch/issues/2640
