### ISSUE TITLE
Is there any way to reduce the release executable size?

### ISSUE THREAD

**Issue by dzcpy** [meilisearch/milli#627]
Hi, thank you for write this awesome tool. I'm currently building a software which requires the package to be within a certain size. However I just tested the example code in the readme, after relase build it takes more than 80M. Besides compressing it using something like UPX, is there anyway to reduce the executable size? Why it take so much space?
Here below is the result from running `cargo bloat --release --crates` using `cargo-bloat`
![image](https://user-images.githubusercontent.com/203980/188693355-be7c5604-5316-4265-8fc6-02de66d2c670.png)

**Comment by Kerollmops** [comment]
Hey @dzcpy,

You can maybe try using [the strip command](https://linux.die.net/man/1/strip) it could probably help. It removes the debug symbols from the binary.

**Comment by dzcpy** [comment]
Hi @Kerollmops, thanks for your quick reply. However I'm using the following cargo config:
```toml
[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*
```
I think symbols has already been striped? I also tried that difference between debug and release modes is only around 10M.

**Comment by Kerollmops** [comment]
Hey @dzcpy,

Unfortunately, I can't help you more than that as I am not an expert on this subject. however, you [can look at this guide repository](https://github.com/johnthagen/min-sized-rust) which will surely help you reduce the binary size furthermore.

I will close this issue as this is not something we want to prioritize any time soon.
Have a nice day 🏝

**Comment by vincent-herlemont** [comment]
I can purpose a solution to reduce the size  ~90% (from `~92.1MiB` to  `8.9MiB`).

The solution is to ignore tokenizing for these languages `"chinese", "hebrew", "japanese", "thai"` ([charabia/Cargo.toml#L28](https://github.com/meilisearch/charabia/blob/59520a0e3299aab188d1a7be27b06bc56d7b1058/Cargo.toml#L28)).

I have purposed a PR here https://github.com/meilisearch/milli/pull/632. This PR seems does not change the current behavior of the crate but allows the possibility to remove the support of the above languages.

- `milli = { path = "../milli/milli" }`: `~92.1MiB` 
- `milli = { path = "../milli/milli", default-features = false  }`: `8.9MiB`

**Comment by vincent-herlemont** [comment]
Just for information ~85% of the size of the binary is taked by [crates/lindera-ipadic](https://crates.io/crates/lindera-ipadic) which used by [meilisearch/charabia/Cargo.toml#L24](https://github.com/meilisearch/charabia/blob/59520a0e3299aab188d1a7be27b06bc56d7b1058/Cargo.toml#L24).
