### ISSUE TITLE
Replace deprecated `set-output` in GitHub actions

### ISSUE THREAD

**Issue by curquiza** [meilisearch/milli#678]
In our GitHub actions, we are using `set-output` command which is deprecated and will be removed.

<img width="1334" alt="Capture d’écran 2022-10-31 à 18 57 38" src="https://user-images.githubusercontent.com/20380692/199077035-c4f3ed69-4d84-445b-b660-e879328e0277.png">

See [this link for example](https://github.com/meilisearch/milli/actions/runs/3354685244)

We need to replace with environment variables, following this GitHub article: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

🔥 Should be done by the end of May 2023 🔥

**Comment by SO-HYBE** [comment]
I can help, assign to me please

**Comment by curquiza** [comment]
Hello @SO-HYBE 

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

For your information, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊

**Comment by SO-HYBE** [comment]
Ok I got your point. Let's do it

**Comment by azzamsa** [comment]
@SO-HYBE Hi. I don't see any opened PR from [you](https://github.com/meilisearch/milli/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3ASO-HYBE). Are you still with this? Or may I take over?

**Comment by pnhatminh** [comment]
@curquiza Hi there.
I have made the change to the workflows according to the presented documentation. You could find my change [here](https://github.com/meilisearch/milli/compare/main...pnhatminh:milli:replace-deprecated-gh-actions)
However, I am not able to trigger any workflow for testing, as it keeps `Waiting for a runner to pick up this job...`
Do you have any suggestion on the testing for this issue?

**Comment by curquiza** [comment]
Hello @pnhatminh can you open a PR so that I can review and merge it? 😊 The changes you made seems ok
