### ISSUE TITLE
Fix ShellCheck errors

### ISSUE THREAD

**Issue by azzamsa** [meilisearch/milli#688]
Hi.

I am running [ShellCheck](https://www.shellcheck.net/) against the shell scripts and fixed the warnings in the PR below:
- https://github.com/meilisearch/milli/pull/687

If that's okay, I plan to add the [ShellCheck action](https://github.com/ludeeus/action-shellcheck#shellcheck) check in the CI.

**Comment by curquiza** [comment]
Hello @azzamsa 
Thanks for the PR!

Also, we would rather not have this additional CI, we don't change the script + we plan to reorganize this repo in the near future. But thanks for the suggestion 😊

**Comment by curquiza** [comment]
Closing this due to lack of answer on the PR, of course feel free to reopen if needed 😊

**Comment by azzamsa** [comment]
> Also, we would rather not have this additional CI, we don't change the script + we plan to reorganize this repo in the near future. But thanks for the suggestion blush

Thanks for your patience. Just returned from vacation.
It is okay 🙂. I will look for other part to contribute.
