### ISSUE TITLE
Incorrect identification of the primary key when it is not directly set

### ISSUE THREAD

**Issue by GregoryConrad** [meilisearch/milli#695]
Hi! I noticed this issue when writing some test cases for my side project over at https://github.com/GregoryConrad/embedded_meilisearch
## The Problem
I've noticed Milli's behavior in identifying a primary key to use (based on the field names) does not always produce the correct results. Take the following JSON document:
```
{
  "id": "1234",
  "video": "https://some-video-provider.com/some-video"
}
```
This works ok; "id" comes before "video" in the document, and it appears milli does the `contains("id")` check through the fields in-order.

Now take the following document.
```
{
  "video": "https://some-video-provider.com/some-video",
  "id": "1234"
}
```
Milli fails to index such a document, _even with an `id` field_.

## Possible Solutions
Having to manually set a primary key for documents that already provide an `id` seems fairly unintuitive; thus, I propose a few other solutions:
1. Manually check to see if there is an `id` field before doing the `contains("id")` check in-order. This option requires the least change. Also, an `id` key is much more likely to occur earlier in a document, and this approach respects that.
2. For all fields that `contains("id")`, choose the one with the smallest string length. This retains consistency with the docs (_not a breaking change_), but also makes a smarter guess as to which field to use (assuming users have field names like `pid` or `fid`, for instance).
3. For all fields that `contains("id")`, choose the one with the smallest Levenshtein distance from `"id"`. This might actually return the same results as solution 2; I would need to read into the algorithm more. Either way, it will _not be a breaking change_, as per the docs.
4. Choose the field with smallest levenshtein distance from `"id"`. Here, the field closest to `id` will be chosen as the primary key. I think this is somewhat a smarter approach than the others. However, this is obviously a breaking change and would require doc updates.

If you have any further ideas, I am all ears. I am also happy to make a PR to fix this issue once a decision has been made on which solution to go forward with.

**Comment by gmourier** [comment]
Hi @GregoryConrad 👋

We have a [product discussion](https://github.com/meilisearch/product/discussions/206) for that very particular subject. I've copied your message into the discussion to continue there.

Thank you!

**Comment by curquiza** [comment]
Hello @gmourier and @GregoryConrad 
Thanks for the report @GregoryConrad this is really appreciated!

I close this issue then in favor of https://github.com/meilisearch/product/discussions/206
