### ISSUE TITLE
Speedup indexing by not using RoaringBitmaps

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/milli#73]
When we are indexing documents we write always insert new ids under the list of words or facets, those ids list are in fact RoaringBitmaps which are fasts and compact lists of integers.

However, if the amount of data in memory reaches a certain threshold we dump it to disk and merge those entries (where the values are RoaringBitmaps) when needed, the problem is that the RoaringBitmap indexing format is a little bit costy and forces us to deserialize it into memory before being able to merge both datastructures.

I propose that we don't use RoaringBitmaps when it is related to datastructures that will merged a lot of time and that must be deserialized for that to happen, and instead use simple list of integers (native endian encoded) and where we will be able to just push the new integers at the end. Note that those integers are the internal documents ids and will be seen once during the indexing process.

**Comment by curquiza** [comment]
Checked with @Kerollmops, already partly implemented
