### ISSUE TITLE
Introduce prefix caching for small query words

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/milli#77]
- [x] Make the Query Tree work with the prefix caches.
- [x] Introduce an fst Set that indicates the prefixes/words that are cached.
- [x] Introduce a database for cached prefixes that gives the corresponding docids.
- [x] Introduce a database for proximities between a whole word and a cached prefix.
- [x] Make the ranking rules work with the prefix caches:
  - [x] Proximity.
  - [x] Attributes.

**Comment by curquiza** [comment]
Related to #42

**Comment by curquiza** [comment]
Dooooone 🎉
